---
# ================== PURPOSE ==================
# Handlers for intrusion detection - Hardened Edition
# - Proper auditd restart handling
# - Audit rule rebuilding
# - Service restart with validation
# =============================================

- name: Alert critical intrusion
  ansible.builtin.uri:
    url: "{{ discord_webhook_url }}"
    method: POST
    body_format: json
    body:
      content: >-
        {{ intrusion_detection_alert_severity_levels.critical }} **CRITICAL INTRUSION DETECTED**

        **Host:** {{ inventory_hostname }}

        **Event:** {{ alert_message }}

        **Time:** {{ ansible_date_time.iso8601 }}
    status_code: [200, 204]
  when: discord_webhook_url is defined
  throttle: 1
  failed_when: false

- name: Alert warning intrusion
  ansible.builtin.uri:
    url: "{{ discord_webhook_url }}"
    method: POST
    body_format: json
    body:
      content: >-
        {{ intrusion_detection_alert_severity_levels.warning }} **Warning: Suspicious Activity**

        **Host:** {{ inventory_hostname }}

        **Event:** {{ alert_message }}

        **Time:** {{ ansible_date_time.iso8601 }}
    status_code: [200, 204]
  when: discord_webhook_url is defined
  throttle: 1
  failed_when: false

- name: Alert info intrusion
  ansible.builtin.uri:
    url: "{{ discord_webhook_url }}"
    method: POST
    body_format: json
    body:
      content: >-
        {{ intrusion_detection_alert_severity_levels.info }} **Info: Detection Event**

        **Host:** {{ inventory_hostname }}

        **Event:** {{ alert_message }}

        **Time:** {{ ansible_date_time.iso8601 }}
    status_code: [200, 204]
  when: discord_webhook_url is defined
  throttle: 1
  failed_when: false

- name: Collect evidence
  ansible.builtin.include_role:
    name: incident_response
    tasks_from: collect_logs.yml
  when: intrusion_detection_auto_collect_evidence | default(true)

- name: Restart log watcher
  ansible.builtin.systemd:
    name: ccdc-log-watcher
    state: restarted
    daemon_reload: true
  when: ansible_os_family != "Windows"

- name: Restart honeypot watcher
  ansible.builtin.systemd:
    name: ccdc-honeypot-watcher
    state: restarted
    daemon_reload: true
  when: ansible_os_family != "Windows"

- name: Restart alert retry daemon
  ansible.builtin.systemd:
    name: ccdc-alert-retry
    state: restarted
    daemon_reload: true
  when: ansible_os_family != "Windows"

- name: Rebuild audit rules
  ansible.builtin.include_tasks:
    file: handlers/rebuild_auditd.yml
  when: ansible_os_family == "RedHat"

- name: Restart auditd
  ansible.builtin.include_tasks:
    file: handlers/restart_auditd.yml
  when: ansible_os_family == "RedHat"
