---
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  
  - name: community.general
    version: ">=8.0.0"
  
  - name: community.windows
    version: ">=2.0.0"
  
  - name: ansible.windows
    version: ">=2.0.0"
  
  # Network device collections
  - name: paloaltonetworks.panos
    version: ">=2.17.0"
  
  - name: cisco.ftd
    version: ">=2.0.0"
  
  - name: vyos.vyos
    version: ">=4.0.0"