[linux_servers]
ubuntu       ansible_host=10.250.20.4  ansible_user=cnm ansible_password=password ansible_become_password=password
oracle_linux ansible_host=10.250.20.30 ansible_user=cnm ansible_password=password ansible_become_password=password

[unix_servers]
free_bsd     ansible_host=10.250.20.10 ansible_user=root ansible_password=toor ansible_become=false

[security_tools]
kali      ansible_host=10.250.40.100 ansible_user=kali ansible_password=kali ansible_become_password=kali
wazu      ansible_host=10.250.40.110 ansible_user=cnm  ansible_password=password ansible_become_password=password
sec_onion ansible_host=10.250.40.120 ansible_user=cnm  ansible_password=password ansible_become_password=password
splunk    ansible_host=10.250.40.130 ansible_user=cnm  ansible_password=password ansible_become_password=password

[windows_devices]
win_19_web ansible_host=10.250.30.3 ansible_user=administrator ansible_password='Cyb3rKitt3ns07!'
win_22_dns ansible_host=10.250.30.5 ansible_user=administrator ansible_password='Cyb3rKitt3ns07!'
win_10     ansible_host=10.250.30.7 ansible_user=cnm           ansible_password=password

[network_devices]
pafw ansible_host=10.250.20.254 ansible_user=admin ansible_password='P@l0Alt0!'
ftd  ansible_host=10.250.30.254 ansible_user=admin ansible_password='Cyb3rKitt3ns07!'
vyos ansible_host=10.250.10.2   ansible_user=vyos  ansible_password='Cyb3rKitt3ns07!'

# Logical groups
[firewalls]
pafw
ftd

[ids_tools]
wazu
sec_onion

[attack_tools]
kali

# Children
[servers:children]
linux_servers
unix_servers
windows_devices

[security_stack:children]
ids_tools
# siem

# Group vars (single block per group)
[linux_servers:vars]
ansible_become=true
ansible_become_method=sudo

[security_tools:vars]
ansible_become=true
ansible_become_method=sudo

[attack_tools:vars]
ansible_become=true
ansible_become_method=sudo

[unix_servers:vars]
ansible_become=false
