---
competition_team_number: 21

# Net 1 (servers)
linux_lan_cidr: 10.250.20.0/24
ecom_private_ip: 10.250.20.20
webmail_private_ip: 10.250.20.30
freebsd_private_ip: 10.250.20.10

# Security net
# Uncomment when Splunk is actually present
# splunk_private_ip: 10.250.40.130

# Windows net
win_lan_cidr: 10.250.30.0/24
win_web_private_ip: 10.250.30.15
ad_private_ip: 10.250.30.25
win_wks_private_ip: 10.250.30.35

# Firewall mgmt IPs (for later automation / documentation)
palo_mgmt_ip: 10.250.20.254
ftd_mgmt_ip: 10.250.30.254
