# Meta for splunk_harden
galaxy_info:
  author: MWCCDC-Team
  description: splunk_harden role scaffolding
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
dependencies: []
