galaxy_info:
  author: MWCCDC Team
  description: Install Splunk Enterprise from package and seed admin password
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
dependencies: []
