# Meta for paloalto_firewall
galaxy_info:
  author: MWCCDC-Team
  description: paloalto_firewall role scaffolding
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
dependencies: []
