---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  config_options:
    defaults:
      retry_files_enabled: false
  playbooks:
    converge: converge.yml
  lint: |
    yamllint -c ../../../../.yamllint.yml .
    ansible-lint
verifier:
  name: testinfra
  directory: tests
