---
- name: restart splunk forwarder
  ansible.builtin.command:
    cmd: "{{ splunk_uf_bin }} restart"
  become: true
  become_user: "{{ splunk_uf_user }}"
  register: uf_restart
  changed_when: true
  failed_when: false

- name: wait for uf mgmt port
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: 8089
    state: started
    delay: 2
    timeout: 120
