---
- name: restart splunk universal_forwarder
  ansible.builtin.command:
    cmd: "{{ splunk_universal_forwarder_bin }} restart"
  become: true
  become_user: "{{ splunk_universal_forwarder_user_effective }}"
  register: uf_restart
  changed_when: true
  failed_when: false

- name: wait for universal_forwarder mgmt port
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: 8089
    state: started
    delay: 2
    timeout: 120
