---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Configure UFW default policies
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: "{{ common_ports.ssh }}"
    proto: tcp