---
# ================== PURPOSE ==================
# Configure Apache on Debian/Ubuntu systems
# - Installs Apache
# - Ensures service is running
# - Sets document root permissions
# =============================================

- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: Ensure Apache is running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Set document root permissions
  ansible.builtin.file:
    path: "{{ web_server_document_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Verify HTTP service is responding
  ansible.builtin.uri:
    url: http://localhost
    status_code: 200
    return_content: false
  register: http_status
  changed_when: false

- name: Verify HTTPS service is responding
  ansible.builtin.uri:
    url: https://localhost
    status_code: 200
    return_content: false
    validate_certs: false
  register: https_status
  changed_when: false
