---
# ================== PURPOSE ==================
# Configure Apache on RedHat/Fedora systems
# - Installs httpd
# - Ensures service is running
# - Sets document root permissions
# =============================================

- name: Install Apache (httpd)
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Ensure httpd is running
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Set document root permissions
  ansible.builtin.file:
    path: "{{ web_server_document_root }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Verify HTTP service is responding
  ansible.builtin.command: "curl -s -o /dev/null -w '%{http_code}' http://localhost"
  register: http_status
  changed_when: false
  failed_when: http_status.stdout != "200"

- name: Verify HTTPS service is responding
  ansible.builtin.command: "curl -sk -o /dev/null -w '%{http_code}' https://localhost"
  register: https_status
  changed_when: false
  failed_when: https_status.stdout != "200"
