---
# ================== PURPOSE ==================
# Default configuration for intrusion detection
# - Alert thresholds and cooldown periods
# - Detection patterns and honeypot locations
# - Tuneable for competition environment
# =============================================

# Alert configuration
intrusion_detection_alert_cooldown_seconds: 300  # 5 min between duplicate alerts
intrusion_detection_alert_severity_levels:
  critical: "🚨"
  warning: "⚠️"
  info: "ℹ️"

# Detection thresholds
intrusion_detection_failed_login_threshold: 5     # Failed logins before alert
intrusion_detection_failed_login_window: 300      # Time window in seconds
intrusion_detection_suspicious_command_alert: true

# Honeypot configuration
intrusion_detection_honeypot_enabled: true
intrusion_detection_honeypot_users:
  - redteam
  - hacker
  - test
intrusion_detection_honeypot_files:
  - /root/.ssh/authorized_keys_backup
  - /etc/shadow.bak
  - /var/www/html/admin.php
intrusion_detection_honeypot_directories:
  - /opt/backup
  - /root/secrets

# Log monitoring
intrusion_detection_log_watch_enabled: true
intrusion_detection_log_watch_interval: 60  # Check every 60 seconds
intrusion_detection_monitored_logs:
  debian:
    - /var/log/auth.log
    - /var/log/syslog
  redhat:
    - /var/log/secure
    - /var/log/messages

# Suspicious patterns (regex)
intrusion_detection_suspicious_patterns:
  - 'nc -[el].*[0-9]+'           # Netcat listeners
  - 'bash -i.*dev/tcp'           # Reverse shell
  - 'python.*socket.*connect'    # Python reverse shell
  - 'perl.*socket.*connect'      # Perl reverse shell
  - 'wget.*\|.*sh'               # Download and execute
  - 'curl.*\|.*bash'             # Download and execute
  - 'chmod \+s'                  # SUID bit manipulation
  - '/etc/passwd'                # Password file access (in commands)
  - '/etc/shadow'                # Shadow file access

# Evidence collection
intrusion_detection_evidence_dir: "{{ incident_dir }}/{{ inventory_hostname }}"
intrusion_detection_auto_collect_evidence: true

# Suppress alerts that would be triggered during honeypot setup by default.
# Set to true to allow sending alerts when honeypot users are created.
intrusion_detection_send_honeypot_setup_alerts: false
