---

# ================== PURPOSE ==================
# Entry point for incident response role
# - Collects logs and scans for suspicious processes
# - Tasks are tagged for selective execution
# =============================================

- name: Collect logs
  include_tasks: collect_logs.yml
  tags: [logs]

- name: Scan for suspicious processes
  include_tasks: scan_processes.yml
  tags: [processes]