---

# ================== PURPOSE ==================
# Backup tasks for Linux hosts
# - Ensures backup_dir exists with secure permissions
# - Archives critical directories (default: /etc, expandable via backup_paths)
# - Skips Windows hosts
# =============================================

- name: Create backup directory
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0700'
  when: ansible_os_family != "Windows"

- name: Backup critical directory
  ansible.builtin.archive:
    path: "{{ item }}"
    dest: "{{ backup_dir }}/PP item | basename }}{{ ansible_date_time.epoch }}.tar.gz"
    format: gz
  loop: "{{ backup_paths }}"
  when: ansible_os_family != "Windows"