---

# PURPOSE: Entry point for common role
# Includes backup + update tasks, tagged for selective runs
- name: Include backup tasks
  include_tasks: backup.yml
  tags: [backup]

- name: Include update tasks
  include_tasks: updates.yml
  tags: [updates]
