---
# ================== PURPOSE ==================
# Honeypot Setup Tasks
# - Creates fake users, files, and directories
# - Configures inotify watches for access detection
# - Triggers alerts on honeypot interaction
# =============================================

- name: Install inotify-tools for file watches
  ansible.builtin.package:
    name: inotify-tools
    state: present
  when: ansible_os_family != "Windows"

- name: Create honeypot users (disabled login)
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/false
    create_home: false
    state: present
  loop: "{{ intrusion_detection_honeypot_users }}"
  when: intrusion_detection_honeypot_enabled | default(true)
  register: intrusion_detection_honeypot_user_create

- name: Create honeypot directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ intrusion_detection_honeypot_directories }}"
  when: intrusion_detection_honeypot_enabled | default(true)

- name: Create honeypot files (fake sensitive data)
  ansible.builtin.copy:
    dest: "{{ item }}"
    content: |
      # HONEYPOT FILE - DO NOT MODIFY
      # This file is monitored for intrusion detection
      # Last modified: {{ ansible_date_time.iso8601 }}
    mode: '0644'
  loop: "{{ intrusion_detection_honeypot_files }}"
  when: intrusion_detection_honeypot_enabled | default(true)

- name: Deploy honeypot alert script
  ansible.builtin.template:
    src: honeypot_alert.sh.j2
    dest: /usr/local/bin/honeypot_alert.sh
    mode: '0755'
  when: intrusion_detection_honeypot_enabled | default(true)

- name: Deploy honeypot watcher systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/ccdc-honeypot-watcher.service
    content: |
      [Unit]
      Description=CCDC Honeypot File Watcher
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/honeypot_watcher.sh
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  when: intrusion_detection_honeypot_enabled | default(true)
  notify: Restart honeypot watcher

- name: Deploy honeypot watcher script
  ansible.builtin.template:
    src: honeypot_watcher.sh.j2
    dest: /usr/local/bin/honeypot_watcher.sh
    mode: '0755'
  when: intrusion_detection_honeypot_enabled | default(true)

- name: Optionally notify that honeypot users were created (only if enabled)
  ansible.builtin.debug:
    msg: "Honeypot users created during setup"
  when:
    - intrusion_detection_send_honeypot_setup_alerts | default(false)
    - intrusion_detection_honeypot_user_create is defined and (intrusion_detection_honeypot_user_create.results | selectattr('changed') | list | length) > 0
  notify: Alert critical intrusion

- name: Enable and start honeypot watcher
  ansible.builtin.systemd:
    name: ccdc-honeypot-watcher
    enabled: true
    state: started
    daemon_reload: true
  when: intrusion_detection_honeypot_enabled | default(true)

- name: Add audit rules for honeypot files
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/ccdc-honeypots.rules
    line: "-w {{ item }} -p wa -k honeypot_access"
    create: true
    mode: '0640'
  loop: "{{ intrusion_detection_honeypot_files }}"
  when:
    - intrusion_detection_honeypot_enabled | default(true)
    - ansible_os_family == "RedHat"
  notify: Restart auditd

- name: Add audit rules for honeypot directories
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/ccdc-honeypots.rules
    line: "-w {{ item }} -p wa -k honeypot_dir_access"
    create: true
    mode: '0640'
  loop: "{{ intrusion_detection_honeypot_directories }}"
  when:
    - intrusion_detection_honeypot_enabled | default(true)
    - ansible_os_family == "RedHat"
  notify: Restart auditd
