---
- name: Bootstrap python libdnf5 bindings (Fedora/RHEL)
  ansible.builtin.raw: dnf install -y python3-libdnf5
  become: true
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Enable EPEL repository (RedHat/Fedora)
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Install fail2ban (RedHat/Fedora)
  ansible.builtin.dnf:
    name: fail2ban
    state: present
  register: fail2ban_dnf
  become: true

- name: Display fail2ban installation result
  ansible.builtin.debug:
    msg: "{{ '✅ fail2ban installed' if (fail2ban_dnf is changed) else '✅ fail2ban already installed' }}"
