---
- name: Bootstrap python libdnf5 bindings (Fedora/RHEL)
  ansible.builtin.raw: dnf install -y python3-libdnf5
  become: true
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Enable EPEL repository (RedHat/Fedora) via dnf CLI
  ansible.builtin.raw: dnf install -y epel-release
  become: true
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Install fail2ban (RedHat/Fedora) via dnf CLI
  ansible.builtin.raw: dnf install -y fail2ban
  become: true
  changed_when: false
  when: ansible_os_family == "RedHat"


- name: Display fail2ban installation result
  ansible.builtin.debug:
    msg: "{{ '✅ fail2ban installed' if (fail2ban_dnf is changed) else '✅ fail2ban already installed' }}"
