---
# Configure Splunk server (receiver + base configuration)
- name: Configure Splunk server
  hosts: monitoring
  become: true
  gather_facts: false

  roles:
  - { role: splunk_configure, tags: ["splunk_configure"] }
  - { role: splunk_content,   tags: ["splunk_content"] }
  - { role: splunk_harden,    tags: ["splunk_harden"] }
