---
# Configure Splunk server (receiver + base configuration)
- name: Configure Splunk server
  hosts: splunk
  become: true
  gather_facts: true

  roles:
    - splunk_configure
    - splunk_content
    - splunk_harden
