---
- name: Install and configure Splunk Universal Forwarders
  hosts: linux_servers:workstations
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather minimal facts (platform detection)
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "min"

  roles:
    - splunk_universal_forwarder
