---
- name: First 15 Minute Baseline
  hosts: all
  gather_facts: true
  vars_files:
    - ../vault.yml

  tasks:

  # ---------------- Linux ----------------
  - name: Update packages (Debian/Ubuntu)
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
    when: ansible_os_family == "Debian"
    become: true

  - name: Update packages (RedHat/Fedora/Oracle)
    ansible.builtin.dnf:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    become: true

  - name: Ensure firewalld is running (Linux)
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"
    become: true

  - name: Allow core services (Linux)
    ansible.posix.firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
      immediate: true
    loop:
      - ssh
      - http
      - https
      - dns
      - smtp
      - pop3
      - ftp
    when: ansible_os_family == "RedHat"
    become: true

  # ---------------- Windows ----------------
  - name: Enable Windows Firewall
    community.windows.win_firewall:
      state: enabled
    when: ansible_os_family == "Windows"

  - name: Allow core inbound ports (Windows)
    community.windows.win_firewall_rule:
      name: "Allow Core Services"
      localport: "{{ item }}"
      action: allow
      direction: in
      protocol: TCP
      state: present
      enabled: true
    loop:
      - 22   # SSH
      - 80   # HTTP
      - 443  # HTTPS
      - 53   # DNS
      - 25   # SMTP
      - 110  # POP3
      - 21   # FTP
    when: ansible_os_family == "Windows"
