---
- name: First 15 Minute Baseline - Linux
  hosts: linux
  become: true
  tags: [baseline, linux, critical]
  
  tasks:
    - name: Create backup directory
      ansible.builtin.file:
        path: /root/ccdc_backup
        state: directory
      tags: [backup, always]
    
    - name: Update packages (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      tags: [updates, slow]

    - name: Update packages (Redhat)
      ansible.builtin.dnf:
        update_cache: yes
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      tags: [updates, slow]

    - name: Configure firewall
      include_role:
        name: firewall
      tags: [firewall, security]
