---
# ================== PURPOSE ==================
# First 15 Minute Baseline (Linux)
# - Creates /root/ccdc_backup
# - Updates packages (Debian/Ubuntu)
# - Configures firewall via role
# =============================================

- name: First 15 Minute Baseline - Linux
  hosts: linux
  become: true
  tags: [baseline, linux, critical]

  tasks:
    - name: Create backup directory
      ansible.builtin.file:
        path: /root/ccdc_backup
        state: directory
        mode: '0700'
      tags: [backup, always]

    - name: Update packages (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      when: ansible_os_family == "Debian"
      tags: [updates, slow]

    - name: Update packages (RedHat)
      ansible.builtin.dnf:
        name: "*"
        state: present
      when: ansible_os_family == "RedHat"
      tags: [updates, slow]

    - name: Configure firewall
      ansible.builtin.include_role:
        name: firewall
      tags: [firewall, security]

    - name: Backup /etc directory
      community.general.archive:
        path: /etc
        dest: /root/ccdc_backup/etc_backup.tar.gz
        mode: '0644'
      tags: [backup, critical]

    - name: Notify team via Discord
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "✅ {{ ansible_playbook_name | default('<playbook>.yml') }} completed at {{ lookup('pipe', 'date') }}"
        status_code: 204
      when: discord_webhook_url is defined
      failed_when: false
      tags: [notify, passive]
