---
# ================== PURPOSE ==================
# Quick Hardening Playbook
# - Applies the hardening role across all hosts
# - Disables unnecessary Linux services
# - Ensures audit logging is enabled (RedHat/Debian)
# - Tagged for selective execution
# =============================================

- name: Hardening
  hosts: linux
  become: true
  roles:
    - role: hardening

- name: Notify team via Discord
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Post hardening completion
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "🛡️ Hardening completed at {{ lookup('pipe', 'date') }}"
        status_code: 204
      when: discord_webhook_url is defined
      failed_when: false
