---
# ================== PURPOSE ==================
# Quick Hardening Playbook
# - Applies the hardening role across all hosts
# - Disables unnecessary Linux services
# - Ensures audit logging is enabled (RedHat/Debian)
# - Tagged for selective execution
# =============================================

- name: Quick Hardening
  hosts: all
  become: true
  roles:
    - role: hardening
      tags: [hardening, security]
