---
# ================== PURPOSE ==================
# Incident Response Playbook
# - Collects key logs for evidence
# - Scans for suspicious processes
# - Tagged for selective execution
# =============================================

- name: Collect Incident Evidence
  hosts: all
  become: true
  tags: [incident_response, ir, evidence]

  tasks:
    - name: Capture auth logs (Debian/Ubuntu)
      ansible.builtin.fetch:
        src: /var/log/auth.log
        dest: ./incidents/{{ inventory_hostname }}/
      when: ansible_os_family == "Debian"

    - name: Capture secure logs (RedHat)
      ansible.builtin.fetch:
        src: /var/log/secure
        dest: ./incidents/{{ inventory_hostname }}/
      when: ansible_os_family == "RedHat"

    - name: Capture syslog (Debian/Ubuntu)
      ansible.builtin.fetch:
        src: /var/log/syslog
        dest: ./incidents/{{ inventory_hostname }}/
      when: ansible_os_family == "Debian"

    - name: Scan for suspicious processes
      include_role:
        name: incident_response
        tasks_from: scan_processes.yml

    - name: Notify team via Discord
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "✅ {{ ansible_playbook_name | default('<playbook>.yml') }} completed at {{ lookup('pipe','date') }}"
        status_code: 204
      when: discord_webhook_url is defined
      ignore_errors: true
      tags: [notify, passive]
