---

# ================== PURPOSE ==================
# Team Notification Playbook
# - Posts a message to Discord via webhook
# =============================================

- name: Send Team Notification
  hosts: localhost
  gather_facts: false
  vars:
    webhook_url: "{{ lookup('env', 'TEAM_WEBHOOK_URL') }}"
    message: "Ansible task completed"

  tasks:
    - name: Send Discord notification
      ansible.builtin.uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "{{ message }}"
        status_code: 204   # Discord returns 204 No Content on success
      when: discord_webhook_url is defined
      ignore_errors: true

