---
# ================== PURPOSE ==================
# Password Reset Playbook - Host-Specific Version
# - Uses individual host_vars for unique passwords
# - Supports multiple accounts per host
# =============================================

- name: Reset Linux Passwords
  hosts: linux
  become: true
  tasks:
    - name: Reset sysadmin password
      ansible.builtin.user:
        name: sysadmin
        password: "{{ new_sysadmin_password | password_hash('sha512') }}"
      when: new_sysadmin_password is defined

    - name: Reset root password
      ansible.builtin.user:
        name: root
        password: "{{ new_root_password | password_hash('sha512') }}"
      when: new_root_password is defined

- name: Reset Splunk Admin Password
  hosts: splunk
  become: true
  tasks:
    - name: Reset Splunk web admin password
      ansible.builtin.shell: |
        /opt/splunk/bin/splunk edit user admin -password '{{ new_admin_password }}' -auth admin:changemenow
      when: new_admin_password is defined
      no_log: true

- name: Reset Windows Passwords
  hosts: windows
  tasks:
    - name: Reset Administrator password
      ansible.windows.win_user:
        name: Administrator
        password: "{{ new_administrator_password }}"
      when: new_administrator_password is defined

- name: Reset Windows 11 UserOne Password
  hosts: windows11_wks
  tasks:
    - name: Reset UserOne password
      ansible.windows.win_user:
        name: UserOne
        password: "{{ new_userone_password }}"
      when: new_userone_password is defined

- name: Display Manual Password Change Instructions
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show manual steps for network devices
      ansible.builtin.debug:
        msg:
          - ""
          - "⚠️  MANUAL PASSWORD CHANGES REQUIRED:"
          - ""
          - "Palo Alto (172.20.242.150):"
          - "  Current: admin / Changeme123"
          - "  New: admin / Zoroark@571!"
          - ""
          - "Cisco FTD (172.20.240.200):"
          - "  Current: admin / !Changeme123"
          - "  New: admin / Mewtwo%150X"
          - ""
          - "VyOS (172.31.21.2):"
          - "  Current: vyos / changeme"
          - "  New: vyos / Taskmast^41X"
          - ""

- name: Send completion notification
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Post to Discord
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "🔑 Password reset completed at {{ lookup('pipe', 'date') }}"
        status_code: [200, 204]
      when: discord_webhook_url is defined
      failed_when: false
