---

# ================== PURPOSE ==================
# Password Reset Playbook
# - Rotates admin/root passwords across hosts
# - Stores new passwords in Ansible Vault
# - Logs changes without exposing secrets
# =============================================
# - Edit vault with: ansible-vault edit group_vars/all/vault.yml
# - Run with: ansible-playbook playbooks/pass_reset.yml --vault-password-file ~/.vault_pass
# - Tags:
#     pass_reset, linux, windows, network, notify
# - Output: Logs reset completion, but never prints passwords


- name: Reset passwords on Linux
  hosts: linux
  become: true
  vars:
    new_pass: "{{ vault_linux_admin_pass }}"
  tasks:
    - name: Reset root password
      ansible.builtin.user:
        name: root
        password: "{{ new_pass | password_hash('sha512') }}"
      tags: [pass_reset, linux]

- name: Reset passwords on Windows
  hosts: windows
  vars:
    new_pass: "{{ vault_windows_admin_pass }}"
  tasks:
    - name: Reset Administrator password
      ansible.windows.win_user:
        name: Administrator
        password: "{{ new_pass }}"
      tags: [pass_reset, windows]

- name: Reset passwords on network devices
  hosts: network
  vars:
    new_pass: "{{ vault_network_admin_pass }}"
  tasks:
    - name: Reset device admin password
      cisco.ios.ios_user:
        name: admin
        configured_password: "{{ new_pass }}"
        update_password: always
      tags: [pass_reset, network]

- name: Notify team via Discord
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Post reset completion
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "🔑 pass_reset.yml completed at {{ lookup('pipe','date') }}"
        status_code: 204
      when: discord_webhook_url is defined
      ignore_errors: true
      tags: [notify, passive]
