---
- name: Reset Linux passwords (standard systems)
  hosts: debian,fedora_webmail
  become: true
  tasks:
    - name: Reset sysadmin password
      ansible.builtin.user:
        name: sysadmin
        password: "{{ vault_linux_sysadmin_new | password_hash('sha512') }}"
    
    - name: Reset root password
      ansible.builtin.user:
        name: root
        password: "{{ vault_linux_root_new | password_hash('sha512') }}"

- name: Reset Splunk passwords
  hosts: splunk
  become: true
  tasks:
    - name: Reset sysadmin password
      ansible.builtin.user:
        name: sysadmin
        password: "{{ splunk_sysadmin_new | password_hash('sha512') }}"
    
    - name: Reset root password
      ansible.builtin.user:
        name: root
        password: "{{ splunk_root_new | password_hash('sha512') }}"
    
    - name: Reset Splunk admin password (web interface)
      ansible.builtin.shell: |
        /opt/splunk/bin/splunk edit user admin \
          -password '{{ splunk_admin_new }}' \
          -auth admin:{{ splunk_admin_default }}
      register: splunk_pass_change
      failed_when: false
      changed_when: splunk_pass_change.rc == 0

- name: Reset Windows passwords
  hosts: windows
  tasks:
    - name: Reset Administrator password
      ansible.windows.win_user:
        name: Administrator
        password: "{{ vault_windows_admin_new }}"
        password_never_expires: true
    
    - name: Reset UserOne password (Win11 workstation)
      ansible.windows.win_user:
        name: UserOne
        password: "{{ vault_windows_userone_new }}"
      when: inventory_hostname == 'windows11_wks'
      ignore_errors: true

- name: Display network device password reset instructions
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Manual password changes required
      ansible.builtin.debug:
        msg:
          - "=============================================="
          - "MANUAL PASSWORD CHANGES REQUIRED"
          - "=============================================="
          - ""
          - "Palo Alto Firewall:"
          - "  URL: https://172.20.242.150"
          - "  Current: admin / Changeme123"
          - "  New: admin / {{ hostvars['paloalto']['paloalto_pass_new'] | default('CompPalo2025!Secure') }}"
          - ""
          - "Cisco FTD Firewall:"
          - "  URL: https://172.20.240.200"
          - "  Current: admin / !Changeme123"
          - "  New: admin / {{ hostvars['cisco_ftd']['cisco_ftd_pass_new'] | default('CompCisco2025!Secure') }}"
          - ""
          - "VyOS Router:"
          - "  SSH: ssh vyos@172.31.21.2"
          - "  Current: vyos / changeme"
          - "  New: {{ hostvars['vyos']['vyos_pass_new'] | default('CompVyos2025!Secure') }}"
          - "  Commands:"
          - "    configure"
          - "    set system login user vyos authentication plaintext-password"
          - "    (enter new password when prompted)"
          - "    commit"
          - "    save"
          - "=============================================="