---

# ================== PURPOSE ==================
# Pre-Check Playbook
# - Validates connectivity and gathers facts
# - Ensures hosts are ready for baseline/hardening
# - Posts completion notice to Discord
# =============================================
# - Run with: ansible-playbook playbooks/pre_check.yml --vault-password-file ~/.vault_pass
# - Tags:
#     pre_check, linux, windows, network, notify
# - Purpose: Verify connectivity and readiness before running baseline/hardening

- name: Pre-check Linux hosts
  hosts: linux
  gather_facts: true
  tasks:
    - name: Ping Linux hosts
      ansible.builtin.ping:
      tags: [pre_check, linux]

    - name: Ensure Python is installed
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt-get update && apt-get install -y python3)
      changed_when: false
      tags: [pre_check, linux]

- name: Pre-check Windows hosts
  hosts: windows
  gather_facts: true
  tasks:
    - name: Ping Windows hosts
      ansible.windows.win_ping:
      tags: [pre_check, windows]

    - name: Verify WinRM connectivity
      ansible.windows.win_command: hostname
      tags: [pre_check, windows]

- name: Pre-check network devices
  hosts: network
  gather_facts: false
  tasks:
    - name: Ping network devices
      ansible.netcommon.net_ping:
      tags: [pre_check, network]

- name: Notify team via Discord
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Post pre-check completion
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "🛠️ pre_check.yml completed at {{ lookup('pipe','date') }}"
        status_code: 204
      when: discord_webhook_url is defined
      ignore_errors: true
      tags: [notify, passive]
