---
- name: Ping localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ping test
      ansible.builtin.ping:

- name: Send Discord notification
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Post test message to Discord
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body:
          content: "✅ Discord webhook test successful at {{ lookup('pipe','date') }}"
        status_code:
          - 200
          - 204
      when: discord_webhook_url is defined
      ignore_errors: true
