---
ansible_user: sysadmin
ansible_python_interpreter: /usr/bin/python3
ansible_become: true
ansible_become_method: sudo
# ansible_become_password: "{{ vault_host_password }}"
#ansible_become_password: "{{ vault_default_password }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_timeout: 10

# Using SSH key authentication (no password needed)
# SSH key: ~/.ssh/ccdc_rsa
# To re-enable password auth, uncomment lines above
