# Meta for common_notify
galaxy_info:
  author: MWCCDC-Team
  description: common_notify role scaffolding
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
dependencies: []
